config/routes.rb
Rails.application.routes.draw do
  resources :personnages
  resources :grades
  resources :races
  get 'home/index'

  root 'home#index'
end

app/models/grade.rb
class Grade < ActiveRecord::Base
	has_many :personnages

def self.getGrade
	all
end
end

app/models/personnage.rb
class Personnage < ActiveRecord::Base
	belongs_to :race
	belongs_to :grade

def self.getPerso
	all
end
end

app/models/race.rb
class Race < ActiveRecord::Base
	has_many :personnages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: [:show, :edit, :update, :destroy]

  # GET /grades
  # GET /grades.json
  def index
    @grades = Grade.all
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to @grade, notice: 'Ajout d\'un grade avec succès.' }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to @grade, notice: 'Modification d\'un grade avec succès.' }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Suppression d\'un grade avec succès.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@personnages = Personnage.getPerso
  	@grades = Grade.getGrade
  end
end

app/controllers/personnages_controller.rb
class PersonnagesController < ApplicationController
  before_action :set_personnage, only: [:show, :edit, :update, :destroy]

  # GET /personnages
  # GET /personnages.json
  def index
    @personnages = Personnage.includes(:race, :grade)
  end

  # GET /personnages/1
  # GET /personnages/1.json
  def show
  end

  # GET /personnages/new
  def new
    @personnage = Personnage.new
  end

  # GET /personnages/1/edit
  def edit
  end

  # POST /personnages
  # POST /personnages.json
  def create
    @personnage = Personnage.new(personnage_params)

    respond_to do |format|
      if @personnage.save
        format.html { redirect_to @personnage, notice: 'Ajout d\'un personnage avec succès.' }
        format.json { render :show, status: :created, location: @personnage }
      else
        format.html { render :new }
        format.json { render json: @personnage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personnages/1
  # PATCH/PUT /personnages/1.json
  def update
    respond_to do |format|
      if @personnage.update(personnage_params)
        format.html { redirect_to @personnage, notice: 'Modification d\'un personnage avec succès.' }
        format.json { render :show, status: :ok, location: @personnage }
      else
        format.html { render :edit }
        format.json { render json: @personnage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personnages/1
  # DELETE /personnages/1.json
  def destroy
    @personnage.destroy
    respond_to do |format|
      format.html { redirect_to personnages_url, notice: 'Suppression d\'un personnage avec succès.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personnage
      @personnage = Personnage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personnage_params
      params.require(:personnage).permit(:nom, :titre, :niveau, :hp, :attaque , :race_id, :grade_id)
    end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: [:show, :edit, :update, :destroy]

  # GET /races
  # GET /races.json
  def index
    @races = Race.all
  end

  # GET /races/1
  # GET /races/1.json
  def show
  end

  # GET /races/new
  def new
    @race = Race.new
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: 'Ajout d\'une race avec succès.' }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1
  # PATCH/PUT /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, notice: 'Modification d\'une race avec succès.' }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url, notice: 'Suppression d\'une race avec succès.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_params
      params.require(:race).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/personnages_helper.rb
module PersonnagesHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/grades/_form.html.erb
<%= simple_form_for @grade do |f| %>
  <% if @grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
      <% @grade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name, label: 'Nom', class: 'form-control' %>

  <%= f.submit 'Enregistrer', class: 'btn btn-primary' %>

<% end %>

app/views/grades/edit.html.erb
<%= render :partial => 'partials/navbar' %>
<h1>Modifier Grade</h1>

<%= render 'form' %>

<%= link_to 'Afficher', @grade, class: 'btn  ' %>
<%= link_to 'Retour', grades_path, class: 'btn  ' %>

app/views/grades/index.html.erb
<%= render :partial => 'partials/navbar' %>
<p id="notice"><%= notice %></p>

<h1>Listes des grades</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grades.each do |grade| %>
      <tr>
        <td><%= grade.name %></td>
        <td><%= link_to 'Afficher', grade , class: 'btn  '%></td>
        <td><%= link_to 'Editer', edit_grade_path(grade) , class: 'btn  '%></td>
        <td><%= link_to 'Supprimer', grade, method: :delete, data: { confirm: 'Etes vous sur ?' } , class: 'btn  '%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouveau Grade', new_grade_path, class: 'btn  ' %>

app/views/grades/new.html.erb
<%= render :partial => 'partials/navbar' %>

<div class="row">
    <div class="col-md-5 col-md-offset-3">
    	
		<h1>Nouveau Grade</h1>

		<%= render 'form' %>

		<%= link_to 'Retour', grades_path , class: 'btn  '%>

    </div>
</div>

app/views/grades/show.html.erb
<%= render :partial => 'partials/navbar' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @grade.name %>
</p>

<%= link_to 'Editer', edit_grade_path(@grade), class: 'btn  ' %> |
<%= link_to 'Retour', grades_path, class: 'btn  ' %>

app/views/home/index.html.erb
<%= render :partial => 'partials/navbar' %>

<div class="row">

	<div class="col-md-9">		
		<h3>Gestionnaire des armées du Mordor</h3>
	</div>

		<%= image_tag('oeil-sauron.png') %>
</div>

<div class="col-md-offset-3">
	<% @grades.each do |grade| %>
		<ul style="float: left; padding: 20px;">
		<li><b><%= grade.name %></b></li>
			<% @personnages.each do |personnage| %>
				<% if personnage.grade_id == grade.id %>
					<li><%= personnage.nom %></li>
				<% end %>
			<% end %>
		</ul>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MordorArmy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/partials/_navbar.html.erb
<nav>
	<div class="nav-wrapper red darken-4">
	  <%= link_to 'Home', root_path, class: 'brand-logo right' %>
	  <ul id="nav-mobile" class="left hide-on-med-and-down">
	    <li><%= link_to 'Gestion des personnages', personnages_path, :style => "text-decoration:none"%></li>
	    <li><%= link_to 'Gestion des grades', grades_path, :style => "text-decoration:none" %></li>
	    <li><%= link_to 'Gestion des races', races_path, :style => "text-decoration:none" %></li>
	  </ul>
	</div>
</nav>

<a href=""></a>

app/views/personnages/_form.html.erb
<%= simple_form_for @personnage do |f| %>

  <% if @personnage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grade.errors.count, "error") %> prohibited this personnage from being saved:</h2>

      <ul>
      <% @personnage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :nom, label: 'Nom', class: 'form-control' %>

  <%= f.input :titre, label: 'Titre', class: 'form-control' %>

  <%= f.input :niveau, label: 'Niveau', class: 'form-control' %>

  <%= f.input :hp, label: 'Point de vie', class: 'form-control' %>

  <%= f.input :attaque, label: 'Points d\'attaque', class: 'form-control' %>

  <%= f.association :race, label: 'Race', class: 'form-control' %>
  
  <%= f.association :grade, label: 'Grade', class: 'form-control' %>

  <%= f.submit 'Enregistrer', class: 'btn btn-primary' %>

<% end %>

app/views/personnages/edit.html.erb
<%= render :partial => 'partials/navbar' %>
<h1>Modifier Personnage</h1>

<%= render 'form' %>

<%= link_to 'Afficher', @personnage , class: 'btn  ' %> |
<%= link_to 'Retour', personnages_path , class: 'btn  ' %>

app/views/personnages/index.html.erb
<%= render :partial => 'partials/navbar' %>
<p id="notice"><%= notice %></p>

<h1>Liste de Personnages</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Titre</th>
      <th>Niveau</th>
      <th>Hp</th>
      <th>Attaque</th>
      <th>Race</th>
      <th>Grade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personnages.each do |personnage| %>
      <tr>
        <td><%= personnage.nom %></td>
        <td><%= personnage.titre %></td>
        <td><%= personnage.niveau %></td>
        <td><%= personnage.hp %></td>
        <td><%= personnage.attaque %></td>
        <td>
            <% race = personnage.race %>
            <% if race.nil? -%>
              aucun
            <% else %>
              <%= race.name %>
            <% end %>
        </td>
        <td>
            <% grade = personnage.grade %>
            <% if grade.nil? -%>
              aucun
            <% else %>
              <%= grade.name %>
            <% end %>          
        </td>
        <td><%= link_to 'Afficher', personnage, class: 'btn  ' %></td>
        <td><%= link_to 'Modifier', edit_personnage_path(personnage), class: 'btn  ' %></td>
        <td><%= link_to 'Supprimer', personnage, method: :delete, data: { confirm: 'Etes vous sure?' }, class: 'btn  ' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouveau Personnage', new_personnage_path , class: 'btn  ' %>

app/views/personnages/new.html.erb
<%= render :partial => 'partials/navbar' %>

<div class="row">
    <div class="col-md-5 col-md-offset-3">
    	
		<h1>Nouveau Personnage</h1>

		<%= render 'form' %>

		<%= link_to 'Retour', personnages_path , class: 'btn  '%>

    </div>
</div>

app/views/personnages/show.html.erb
<%= render :partial => 'partials/navbar' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @personnage.nom %>
</p>

<p>
  <strong>Titre:</strong>
  <%= @personnage.titre %>
</p>

<p>
  <strong>Niveau:</strong>
  <%= @personnage.niveau %>
</p>

<p>
  <strong>Hp:</strong>
  <%= @personnage.hp %>
</p>

<p>
  <strong>Attaque:</strong>
  <%= @personnage.attaque %>
</p>

<p>
  <strong>Race :</strong>  
  <% race = @personnage.race %>
  <% if race.nil? -%>
    aucun
  <% else %>
    <%= race.name %>
  <% end %>
</p>

<p>
  <strong>Grade :</strong>  
  <% grade = @personnage.grade %>
  <% if grade.nil? -%>
    aucun
  <% else %>
    <%= grade.name %>
  <% end %>
</p>

<%= link_to 'Modifier', edit_personnage_path(@personnage) , class: 'btn  ' %> |
<%= link_to 'Retour', personnages_path , class: 'btn  ' %>

app/views/races/_form.html.erb
<%= simple_form_for @race do |f| %>
  <% if @race.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@race.errors.count, "error") %> prohibited this race from being saved:</h2>

      <ul>
      <% @race.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name, label: 'Nom', class: 'form-control' %>

  <%= f.submit 'Enregistrer', class: 'btn btn-primary' %>

<% end %>

app/views/races/edit.html.erb
<%= render :partial => 'partials/navbar' %>
<h1>Editing Race</h1>

<%= render 'form' %>

<%= link_to 'Afficher', @race %> |
<%= link_to 'Retour', races_path %>

app/views/races/index.html.erb
<%= render :partial => 'partials/navbar' %>
<p id="notice"><%= notice %></p>

<h1>Listes des races</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @races.each do |race| %>
      <tr>
        <td><%= race.name %></td>
        <td><%= link_to 'Afficher', race , class: 'btn  '%></td>
        <td><%= link_to 'Modifier', edit_race_path(race) , class: 'btn  '%></td>
        <td><%= link_to 'Supprimer', race, method: :delete, data: { confirm: 'Etes vous sur?' } , class: 'btn  '%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouvelle race', new_race_path, class: 'btn  ' %>

app/views/races/new.html.erb
<%= render :partial => 'partials/navbar' %>

<div class="row">
    <div class="col-md-5 col-md-offset-3">
    	
		<h1>Nouvelle Race</h1>

		<%= render 'form' %>

		<%= link_to 'Retour', races_path , class: 'btn  '%>

    </div>
</div>

app/views/races/show.html.erb
<%= render :partial => 'partials/navbar' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @race.name %>
</p>

<%= link_to 'Modifier', edit_race_path(@race) %> |
<%= link_to 'Retour', races_path %>